name: orp_v2
channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - libiconv
  - python>=3.6
  - ruby
  - ca-certificates
  - gmp
  - jemalloc>=5.1.0
  - make=4.2.1=0
  - mpc
  - mpfr
  - ncurses
  - openssl
  - glib
  - icu
  - libffi
  - libgfortran
  - libpng
  - libxcb
  - libxml2
  - qt
  - seaborn
  - readline
  - yaml==0.1.7
  - zlib==1.2.11=0
  - cloog
  - isl
  - libgcc>=5.6.0
  - salmon>=0.10.2
  - seqtk
  - trinity
  - spades
  - busco
  - blast
  - hmmer
  - samtools
  - blat
  - parallel
  - last
  - rcorrector
  - mcl
  - abyss>=2.0.1
  - python-igraph
  - r-base==3.4.3
  - r==3.4.3
  - diamond
  - cd-hit
  - pip:
    - bioformats==0.1.15
    - biopython
    - cvxopt
    - cython
    - fastaindex==0.11rc7
    - future==0.16.0
    - h5py==2.8.0
    - numpy>=1.14.3
    - pandas
    - pip==10.0.1
    - python-dateutil==2.7.3
    - scipy
    - setuptools
    - wheel
    - matplotlib
