name: orp
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - libiconv
  - ruby
  - ca-certificates
  - gmp=6.1.2=0
  - jemalloc>=5.1.0
  - make=4.2.1=0
  - mpc=1.0.3=4
  - mpfr=3.1.5=0
  - ncurses=5.9=10
  - openssl=1.0.2l=0
  - cairo=1.12.18=6
  - cycler=0.10.0=py35_0
  - dbus=1.10.10=0
  - expat=2.1.0=0
  - fontconfig=2.11.1=6
  - freetype=2.5.5=1
  - glib=2.43.0=1
  - gst-plugins-base=1.8.0=0
  - gstreamer=1.8.0=0
  - harfbuzz=0.9.39=1
  - icu
  - libffi=3.2.1=0
  - libgfortran=3.0.0=1
  - libpng=1.6.22=0
  - libxcb=1.12=1
  - libxml2=2.9.2=0
  - mkl=11.3.3=0
  - pango=1.39.0=1
  - pixman=0.32.6=0
  - pyparsing=2.1.4=py35_0
  - pyqt=4.11.4=py35_4
  - pytz=2016.7=py35_0
  - qt=4.8.7=4
  - seaborn=0.7.1=py35_0
  - sip=4.18=py35_0
  - six=1.10.0=py35_0
  - sqlite=3.13.0=0
  - tk=8.5.18=0
  - xz=5.2.2=0
  - readline=6.2=0
  - yaml=0.1.6=0
  - zlib=1.2.11=0
  - cloog=0.18.0=0
  - isl=0.12.2=0
  - libgcc>=7.2.0
  - salmon>=0.10.2
  - seqtk
  - trinity
  - spades
  - busco
  - blast
  - hmmer
  - samtools
  - blat
  - parallel
  - last
  - rcorrector
  - mcl
  - abyss>=2.0.1
  - pip:
    - shmlast
    - bioformats==0.1.15
    - biopython
    - cvxopt
    - fastaindex==0.11rc7
    - future==0.16.0
    - h5py==2.8.0
    - numpy
    - pandas
    - pip==10.0.1
    - pyfaidx==0.5.3.1
    - python-dateutil==2.7.3
    - python-igraph==0.7.1.post6
    - pyvcf==0.6.8
    - scipy
    - setuptools
    - wheel
    - matplotlib
