name: orp_v2
channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - python>=3.6
  - ruby
  - jemalloc>=5.1.0
  - make=4.2.1=0
  - ncurses
  - glib
  - yaml==0.1.7
  - zlib==1.2.11=0
  - libgcc>=5.6.0
  - salmon>=0.10.2
  - seqtk
  - trinity>=2.6.6
  - spades>=3.12.0
  - busco>=3.0.1
  - blast>=2.6.0
  - hmmer
  - samtools>=1.9
  - blat
  - parallel
  - last
  - rcorrector>=1.0.2
  - mcl
  - abyss>=2.1.0
  - python-igraph
  - r-base
  - r==3.4.3
  - diamond
  - cd-hit
  - pip:
    - biopython
    - cvxopt
    - cython
    - numpy>=1.14.3
    - pandas
    - pip==10.0.1
    - scipy
